### ISSUE TITLE
`dep ensure` warning

### ISSUE THREAD

**Issue by MikeMcQuaid** [caarlos0/fork-cleaner#12]
Hi @caarlos0, thanks for the tool! FYI it was added to Homebrew/homebrew-core in https://github.com/Homebrew/homebrew-core/pull/27805 so you can remove it from your tap if you desire.

When running `dep ensure` we receive the following warning:

```
==> dep ensure
dep: WARNING: unknown field in manifest: dependencies
```

Just wanted to let you know. Thanks again!

**Comment by caarlos0** [comment]
Oh, that's nice! Thanks!

Will do it asap

**Comment by ilovezfs** [comment]
Thanks for fixing that @caarlos0!

**Comment by MikeMcQuaid** [comment]
Agreed, thanks for the quick turnaround!

**Comment by caarlos0** [comment]
Thanks for adding it to the core :)
