### ISSUE TITLE
Fails if you have a forked repo with a different name from its upstream

### ISSUE THREAD

**Issue by rwhogg** [caarlos0/fork-cleaner#23]
I have a repo named [gulp-es5validate](https://github.com/rwhogg/gulp-es5validate), which is forked from an upstream repo named [gulp-jsvalidate](https://github.com/sindresorhus/gulp-jsvalidate).

Running `fork-cleaner --token <token>` produces the following error message and an exit status of 1: 
> GET https://api.github.com/repos/sindresorhus/gulp-es5validate/compare/master...rwhogg:master: 404 Not Found []

Blacklisting the repo by either name does not change the result.

To be clear, I don't want to delete this fork, but this error prevents me from seeing others that I might want to.

**Comment by caarlos0** [comment]
thanks, fixed
