### ISSUE TITLE
socket :: permission denied

### ISSUE THREAD

**Issue by Ace-Cassidy** [caarlos0/fork-cleaner#26]
After generating a token with all repo and delete repo access

Running:
```fork-cleaner --token 878678dfeae463e33bb735209bd164844de1d224```

Returns the following error:
```Get "https://api.github.com/user/repos?affiliation=owner&per_page=100": dial tcp: lookup api.github.com on [::1]:53: dial udp [::1]:53: socket: permission denied```

Note that I have since removed this access token

**Comment by BrunnerLivio** [comment]
Seems to be a snap issue. Not quite sure how to workaround this issue, though downloading the `.deb` package directly and installing it via `sudo dpkg -i ~/Downloads/fork-cleaner_<VERSION>_linux_amd64.deb` has worked for me.

**Comment by caarlos0** [comment]
can you try again with latest?

**Comment by BrunnerLivio** [comment]
@caarlos0 Uninstalled the Debian package and re-installed it with Snap. Seems to be resolved! Great job! :tada:

**Comment by caarlos0** [comment]
Thanks for help testing @BrunnerLivio 🙏
