### ISSUE TITLE
Fails with 404

### ISSUE THREAD

**Issue by bep** [caarlos0/fork-cleaner#31]
Not sure what happened, but when I run it, it exits after printing this:

```bash
GET https://api.github.com/repos/caddyserver/caddy/compare/master...bep:master: 404 No common ancestor between master and bep:master. []
```

I have plenty of other forks (I may have the world record in forks).

**Comment by caarlos0** [comment]
https://github.com/caddyserver/caddy/compare/master...bep:master

<img width="595" alt="image" src="https://user-images.githubusercontent.com/245435/90403515-79f43900-e077-11ea-8c07-84a16469092e.png">


seems like either of them had their history rewritten... weird... will ignore 404s there for now.

thanks for reporting :)

**Comment by bep** [comment]
>seems like either of them had their history rewritten... weird... 

I you mean "push -f", that is more common than you think.

**Comment by caarlos0** [comment]
also possible hehe
