### ISSUE TITLE
The "behind the upstream repo" don't work

### ISSUE THREAD

**Issue by bep** [caarlos0/fork-cleaner#32]
```
are even with or behind the upstream repo (customizable via --exclude-commits-ahead).
```

I managed to spot it before I hit "yes sir!", but would not expect this repo to be included:

https://github.com/bep/png-crc-fix

**Comment by caarlos0** [comment]
weird, just tried here and it works 🤔

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: os.Getenv("GITHUB_TOKEN")})
	tc := oauth2.NewClient(ctx, ts)
	client := github.NewClient(tc)

	commits, _, err := client.Repositories.CompareCommits(
		ctx,
		"landaire",
		"png-crc-fix",
		"master",
		"bep:master",
	)

	fmt.Println(err, *commits.AheadBy, *commits.BehindBy)
}
```

should print `<nil> 3 0`

**Comment by caarlos0** [comment]
I really have no idea 🤔

**Comment by bep** [comment]
I may have "read it wrong"; does every repo that gets printed before the yes/no prompt get deleted? Or is it another step?

**Comment by caarlos0** [comment]
hmm.. in this example, its the ones I have selected:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/245435/90780405-b83a6400-e2d4-11ea-9167-3fffc248b321.png">

not sure which params you used, `--show-exclusion-reason` prints more things.. maybe its a bit confusing...

**Comment by bep** [comment]
Just tested it again:

![image](https://user-images.githubusercontent.com/394382/90801883-c6a96f80-e316-11ea-8852-2a4f87c8c76f.png)

I didn't use any param.

**Comment by caarlos0** [comment]
Now you can select which ones you want to delete and it'll show details for each of them. Hopefully this "resolves" this issue.

Closing but feel free to comment or reopen if needed.
