### ISSUE TITLE
Exclude forks where its upstream is deleted?

### ISSUE THREAD

**Issue by filippog** [caarlos0/fork-cleaner#40]
Hi,
thank you for fork-cleaner!

Sometimes I may fork repos at some point in time and its upstream fork then gets deleted, thus I'd like to keep these repos for archival purposes. I didn't check the code but this condition doesn't seem to be explicitly mentioned in the README, will these forks be deleted too?

**Comment by caarlos0** [comment]
You can now choose which repos to delete one by one. But this was handled before too...
