### ISSUE TITLE
public SAML repo forks break the CLI

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [caarlos0/fork-cleaner#44]
👋🏽 heyo, neat tool!

### What
Running the tool on a fork of a SAML repo results in the following error message:

```bash
Error gathering the repository list: failed to get repository's issues: CamiloGarciaLaRotta/rest-api-description: GET https://api.github.com/repos/github/rest-api-description/issues?creator=CamiloGarciaLaRotta&per_page=100: 403 Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization. [].
Check the log file for more details.
```

A couple of things:
- the organization for which to authorize the PAT is not present in the list
- it would be neat if one could still access forks from non SAML orgs. I don't necessarily want to authorize the PAT for every org
- the log file is empty

The good news is that once the PAT is authorized it works as expected 🎉

**Comment by Cathryne** [comment]
> the log file is empty

I observed that well on macOS Catalina 10.15.7 (19H15), both for the `fork-cleaner.log` file that apears in the current working directory, as well as the empty `Library/Logs/Homebrew/fork-cleaner` directory.

**Comment by caarlos0** [comment]
hey, thanks for opening this

happy to review a pr fixing this! 🙏
