### ISSUE TITLE
Do not delete forks with open upstream pull requests?

### ISSUE THREAD

**Issue by andreynering** [caarlos0/fork-cleaner#6]
Hi, thanks very much for this lib.

Even if it was not updated after a month, it the fork holds a pull request to upstream, it would be better not to delete it. Some PRs may take long time to be reviewed, but still require changes before a merge.

Alternatively, the cli could accept a `--exclude` flag, to blacklist some repos. Example:

```
fork-cleaner --token "..." --exclude="a-repo,another-repo,third-repo"
```

**Comment by caarlos0** [comment]
Yeah, seems like a good idea!

**Comment by caarlos0** [comment]
I added the `--exclude` option. The other part will take some time, I'll do it when I can 👍 

Thanks!

**Comment by andreynering** [comment]
Thanks

**Comment by MikeMcQuaid** [comment]
I've opened a PR for this in https://github.com/caarlos0/fork-cleaner/pull/13.
