### ISSUE TITLE
Display issues when more than one screen

### ISSUE THREAD

**Issue by KenMacD** [caarlos0/fork-cleaner#67]
When the list of forks is longer than one screen it is not displayed correctly, and scrolling doesn't work properly.

**Comment by felipecrs** [comment]
Here is a recording, and I turned off my second monitor for the test:

https://user-images.githubusercontent.com/29582865/229126670-ba191482-66bb-4d12-8b54-5e7a4a7860f7.mp4

**Comment by caarlos0** [comment]
this should be addressed by #64

**Comment by caarlos0** [comment]
fixed on main
