### ISSUE TITLE
Repository comparison fail when default branches have no common ancestor

### ISSUE THREAD

**Issue by jack1142** [caarlos0/fork-cleaner#87]
I get this error for one of the forks I have:
```
Error gathering the repository list: failed to compare repository with upstream: jack1142/compose: GET https://api.github.com/repos/docker/compose/compare/v2...jack1142:master: 404 No common ancestor between v2 and jack1142:master. [].
```

It appears that this fork has been created when a different branch was the default branch *and* the branch that is now the default branch is completely new (created without a base, e.g. with `--orphan`).

**Comment by osama-raddad** [comment]
same problem here

**Comment by caarlos0** [comment]
happy to review a pr for this
